
###
POST http://localhost:5000/api/authen/requestToken
Content-Type: application/json

{ 
    "user": "wk",
    "password": "1234"
}

###

GET http://localhost:5000/api/hello/hi
Accept: application/json
Authorization: Bearer ssss